services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb/Meru
    ports:
      - '4000:3000'
    networks:
      - backend
      # - tunnel
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:4.4
    container_name: mongodb-Softdev
    restart: always
    ports:
      - '27016:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
  
  minio:
    image: minio/minio:latest
    ports:
      - "7000:9000"
      - "7001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - minio-data:/data/object
    command: server --address ":9001" --console-address ":9000" /data
    restart: always
    

networks:
  backend:
  # tunnel:
  #   external: true

volumes:
  mongo-data:
  minio-data: