services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb/Meru
    ports:
      - '4000:3000'
    networks:
      - backend
      - tunnel
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - '27016:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

networks:
  backend:
  tunnel:
    external: true

volumes:
  mongo-data: