services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 3002:27017
    volumes:
      - mongo-data:/data/db

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - minio-data:/minio
    command: server --address ":9001" --console-address ":9000" /data
    restart: always

volumes:
  mongo-data:
  minio-data: